name: zVoteParty
authors: 
  - Maxlego08
  - Abasing (Zamin Ali)
  - NaysKutzu
main: fr.maxlego08.zvoteparty.ZVotePartyPlugin
softdepend: [PlaceholderAPI, Votifier, zMenu]
version: '${project.version}'
website: https://github.com/Abasing/zVotePartyx/releases
api-version: 1.20
commands:
